package ugh;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.Enumeration;
import java.util.jar.Attributes;
import java.util.jar.JarFile;
import java.util.jar.Manifest;

/*
DO NOT CHANGE THIS FILE, IT'S GENERATED BY ANT!
 */
public class Version {
    public static String BUILDDATE = "builddate";
    static {
        @SuppressWarnings("rawtypes")
        Enumeration resEnum;
        try {
            resEnum = Thread.currentThread().getContextClassLoader().getResources(JarFile.MANIFEST_NAME);
            while (resEnum.hasMoreElements()) {
                try {
                    URL url = (URL) resEnum.nextElement();
                    InputStream is = url.openStream();
                    if (is != null) {
                        Manifest manifest = new Manifest(is);
                        Attributes mainAttribs = manifest.getMainAttributes();
                        String name = mainAttribs.getValue("name");
                        if (name != null && name.contains("ugh")) {
                            String date = mainAttribs.getValue("Implementation-Build-Date");
                            if (date != null) {
                                BUILDDATE = date;
                            }
                        }
                    }
                } catch (Exception e) {
                    // Silently ignore wrong manifests on classpath?
                }
            }
        } catch (IOException e1) {
            // Silently ignore wrong manifests on classpath?
        }
    }
    private static Package aPackage = Version.class.getPackage();
    public final static String VERSION = "ugh-3.0";
    public final static String BUILDVERSION = "ugh-3.0-" + aPackage.getImplementationVersion();
    public static String PROGRAMNAME = "Goobi";

}
