package ugh;

import java.io.IOException;
import java.net.URL;
import java.util.jar.Attributes;
import java.util.jar.Manifest;

/*
DO NOT CHANGE THIS FILE, IT'S GENERATED BY ANT!
 */
public class Version {
    public static String BUILDDATE = "builddate";

    static {
        Class clazz = Version.class;
        String className = clazz.getSimpleName() + ".class";
        String classPath = clazz.getResource(className).toString();
        if (!classPath.startsWith("jar")) {

            String manifestPath = classPath.substring(0, classPath.lastIndexOf("!") + 1) + "/META-INF/MANIFEST.MF";
            try {
                Manifest manifest;
                manifest = new Manifest(new URL(manifestPath).openStream());
                Attributes mainAttribs = manifest.getMainAttributes();
                String date = mainAttribs.getValue("Implementation-Build-Date");
                if (date != null) {
                    BUILDDATE = date;
                }
            } catch (IOException e) {
                //            // Silently ignore wrong manifests on classpath?

            }

            //    static {
            //        URL url = ((URLClassLoader) Version.class.getClassLoader()).findResource("META-INF/MANIFEST.MF");
            //        try {
            //            InputStream is = url.openStream();
            //            if (is != null) {
            //                Manifest manifest = new Manifest(is);
            //            }
            //        } catch (Exception e) {
            //            // Silently ignore wrong manifests on classpath?
            //        }
        }
    }

    private static Package aPackage = Version.class.getPackage();
    public final static String VERSION = "ugh-3.0";
    public final static String BUILDVERSION = "ugh-3.0-" + aPackage.getImplementationVersion();
    public static String PROGRAMNAME = "Goobi";

}
