package ugh;

import java.io.InputStream;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.jar.Attributes;
import java.util.jar.Manifest;

/*
DO NOT CHANGE THIS FILE, IT'S GENERATED BY ANT!
 */
public class Version {
    public static String BUILDDATE = "builddate";
    static {
        URL url = ((URLClassLoader) Version.class.getClassLoader()).findResource("META-INF/MANIFEST.MF");
        try {
            InputStream is = url.openStream();
            if (is != null) {
                Manifest manifest = new Manifest(is);
                Attributes mainAttribs = manifest.getMainAttributes();
                String date = mainAttribs.getValue("Implementation-Build-Date");
                if (date != null) {
                    BUILDDATE = date;
                }
            }
        } catch (Exception e) {
            // Silently ignore wrong manifests on classpath?
        }
    }
    private static Package aPackage = Version.class.getPackage();
    public final static String VERSION = "ugh-3.0";
    public final static String BUILDVERSION = "ugh-3.0-" + aPackage.getImplementationVersion();
    public static String PROGRAMNAME = "Goobi";

}
